spring.application.name: tracing-zipkin-server

spring.cloud.stream.kafka.binder.brokers: 1172.28.3.159:9092,172.28.3.158:9092
spring.cloud.stream.kafka.binder.zkNodes: 172.28.3.169:2181/kafkaroot

spring.sleuth.enabled: false
zipkin.storage.type: mysql
spring.datasource.schema[0]: classpath:/mysql.sql
spring.datasource.url: jdbc:mysql://172.28.3.159:3306/zipkin?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
spring.datasource.username: canal
spring.datasource.password: canal
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.initialize: true
spring.datasource.continue-on-error: true