spring.application.name: tracing-consumer-service
server.port: 8081

spring.sleuth.sampler.percentage: 1.0


spring.cloud.stream.kafka.binder.brokers: 1172.28.3.159:9092,172.28.3.158:9092
spring.cloud.stream.kafka.binder.zkNodes: 172.28.3.169:2181/kafkaroot
